# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_OpenHand.ui'
#
# Created: Tue Oct 25 13:54:19 2016
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_OpenHand(object):
    def setupUi(self, OpenHand):
        OpenHand.setObjectName(_fromUtf8("OpenHand"))
        OpenHand.resize(745, 529)
        self.centralwidget = QtGui.QWidget(OpenHand)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.teOutput = QtGui.QTextEdit(self.centralwidget)
        self.teOutput.setGeometry(QtCore.QRect(140, 10, 591, 81))
        self.teOutput.setObjectName(_fromUtf8("teOutput"))
        self.pbStartOpenRAVE = QtGui.QPushButton(self.centralwidget)
        self.pbStartOpenRAVE.setGeometry(QtCore.QRect(10, 10, 121, 27))
        self.pbStartOpenRAVE.setObjectName(_fromUtf8("pbStartOpenRAVE"))
        self.tabWidget_2 = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget_2.setGeometry(QtCore.QRect(10, 90, 731, 391))
        self.tabWidget_2.setTabShape(QtGui.QTabWidget.Triangular)
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.pbRLoadHand = QtGui.QPushButton(self.tab_5)
        self.pbRLoadHand.setEnabled(True)
        self.pbRLoadHand.setGeometry(QtCore.QRect(300, 50, 51, 31))
        self.pbRLoadHand.setObjectName(_fromUtf8("pbRLoadHand"))
        self.label_23 = QtGui.QLabel(self.tab_5)
        self.label_23.setGeometry(QtCore.QRect(10, 50, 91, 30))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.cBRSelHand = QtGui.QComboBox(self.tab_5)
        self.cBRSelHand.setGeometry(QtCore.QRect(110, 50, 181, 30))
        self.cBRSelHand.setEditable(False)
        self.cBRSelHand.setObjectName(_fromUtf8("cBRSelHand"))
        self.label_25 = QtGui.QLabel(self.tab_5)
        self.label_25.setGeometry(QtCore.QRect(10, 10, 91, 30))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.pbRLoadExp = QtGui.QPushButton(self.tab_5)
        self.pbRLoadExp.setEnabled(True)
        self.pbRLoadExp.setGeometry(QtCore.QRect(300, 10, 51, 31))
        self.pbRLoadExp.setObjectName(_fromUtf8("pbRLoadExp"))
        self.label_26 = QtGui.QLabel(self.tab_5)
        self.label_26.setGeometry(QtCore.QRect(370, 10, 51, 30))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.cBRLoadObject = QtGui.QComboBox(self.tab_5)
        self.cBRLoadObject.setGeometry(QtCore.QRect(470, 10, 181, 30))
        self.cBRLoadObject.setEditable(False)
        self.cBRLoadObject.setObjectName(_fromUtf8("cBRLoadObject"))
        self.pbRLoadObject = QtGui.QPushButton(self.tab_5)
        self.pbRLoadObject.setGeometry(QtCore.QRect(660, 10, 51, 31))
        self.pbRLoadObject.setObjectName(_fromUtf8("pbRLoadObject"))
        self.cBRLoadExp = QtGui.QComboBox(self.tab_5)
        self.cBRLoadExp.setEnabled(True)
        self.cBRLoadExp.setGeometry(QtCore.QRect(110, 10, 181, 30))
        self.cBRLoadExp.setObjectName(_fromUtf8("cBRLoadExp"))
        self.pbRGrasp = QtGui.QPushButton(self.tab_5)
        self.pbRGrasp.setGeometry(QtCore.QRect(310, 110, 111, 31))
        self.pbRGrasp.setObjectName(_fromUtf8("pbRGrasp"))
        self.pbRInitialPosture = QtGui.QPushButton(self.tab_5)
        self.pbRInitialPosture.setGeometry(QtCore.QRect(660, 50, 51, 31))
        self.pbRInitialPosture.setObjectName(_fromUtf8("pbRInitialPosture"))
        self.cBRInitialPosture = QtGui.QComboBox(self.tab_5)
        self.cBRInitialPosture.setGeometry(QtCore.QRect(470, 50, 181, 31))
        self.cBRInitialPosture.setEditable(False)
        self.cBRInitialPosture.setObjectName(_fromUtf8("cBRInitialPosture"))
        self.label_46 = QtGui.QLabel(self.tab_5)
        self.label_46.setGeometry(QtCore.QRect(370, 50, 101, 31))
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.label_55 = QtGui.QLabel(self.tab_5)
        self.label_55.setGeometry(QtCore.QRect(420, 230, 148, 31))
        self.label_55.setAlignment(QtCore.Qt.AlignCenter)
        self.label_55.setObjectName(_fromUtf8("label_55"))
        self.textB1G = QtGui.QTextEdit(self.tab_5)
        self.textB1G.setGeometry(QtCore.QRect(100, 230, 100, 31))
        self.textB1G.setObjectName(_fromUtf8("textB1G"))
        self.label_57 = QtGui.QLabel(self.tab_5)
        self.label_57.setGeometry(QtCore.QRect(200, 230, 149, 31))
        self.label_57.setAlignment(QtCore.Qt.AlignCenter)
        self.label_57.setObjectName(_fromUtf8("label_57"))
        self.textA1G = QtGui.QTextEdit(self.tab_5)
        self.textA1G.setGeometry(QtCore.QRect(100, 180, 100, 31))
        self.textA1G.setObjectName(_fromUtf8("textA1G"))
        self.textC2G = QtGui.QTextEdit(self.tab_5)
        self.textC2G.setGeometry(QtCore.QRect(320, 280, 100, 31))
        self.textC2G.setObjectName(_fromUtf8("textC2G"))
        self.label_58 = QtGui.QLabel(self.tab_5)
        self.label_58.setGeometry(QtCore.QRect(-20, 180, 148, 31))
        self.label_58.setAlignment(QtCore.Qt.AlignCenter)
        self.label_58.setObjectName(_fromUtf8("label_58"))
        self.label_60 = QtGui.QLabel(self.tab_5)
        self.label_60.setGeometry(QtCore.QRect(-20, 230, 148, 31))
        self.label_60.setAlignment(QtCore.Qt.AlignCenter)
        self.label_60.setObjectName(_fromUtf8("label_60"))
        self.textB3G = QtGui.QTextEdit(self.tab_5)
        self.textB3G.setGeometry(QtCore.QRect(540, 230, 100, 31))
        self.textB3G.setObjectName(_fromUtf8("textB3G"))
        self.label_61 = QtGui.QLabel(self.tab_5)
        self.label_61.setGeometry(QtCore.QRect(200, 280, 149, 31))
        self.label_61.setAlignment(QtCore.Qt.AlignCenter)
        self.label_61.setObjectName(_fromUtf8("label_61"))
        self.label_64 = QtGui.QLabel(self.tab_5)
        self.label_64.setGeometry(QtCore.QRect(-20, 330, 149, 31))
        self.label_64.setAlignment(QtCore.Qt.AlignCenter)
        self.label_64.setObjectName(_fromUtf8("label_64"))
        self.textD1G = QtGui.QTextEdit(self.tab_5)
        self.textD1G.setGeometry(QtCore.QRect(100, 330, 100, 31))
        self.textD1G.setObjectName(_fromUtf8("textD1G"))
        self.label_65 = QtGui.QLabel(self.tab_5)
        self.label_65.setGeometry(QtCore.QRect(200, 330, 149, 31))
        self.label_65.setAlignment(QtCore.Qt.AlignCenter)
        self.label_65.setObjectName(_fromUtf8("label_65"))
        self.textD2G = QtGui.QTextEdit(self.tab_5)
        self.textD2G.setGeometry(QtCore.QRect(320, 330, 100, 31))
        self.textD2G.setObjectName(_fromUtf8("textD2G"))
        self.textB2G = QtGui.QTextEdit(self.tab_5)
        self.textB2G.setGeometry(QtCore.QRect(320, 230, 100, 31))
        self.textB2G.setObjectName(_fromUtf8("textB2G"))
        self.label_71 = QtGui.QLabel(self.tab_5)
        self.label_71.setGeometry(QtCore.QRect(10, 150, 111, 20))
        self.label_71.setObjectName(_fromUtf8("label_71"))
        self.textA2G = QtGui.QTextEdit(self.tab_5)
        self.textA2G.setGeometry(QtCore.QRect(320, 180, 100, 31))
        self.textA2G.setObjectName(_fromUtf8("textA2G"))
        self.label_59 = QtGui.QLabel(self.tab_5)
        self.label_59.setGeometry(QtCore.QRect(200, 180, 148, 31))
        self.label_59.setAlignment(QtCore.Qt.AlignCenter)
        self.label_59.setObjectName(_fromUtf8("label_59"))
        self.textA3G = QtGui.QTextEdit(self.tab_5)
        self.textA3G.setGeometry(QtCore.QRect(540, 180, 100, 31))
        self.textA3G.setObjectName(_fromUtf8("textA3G"))
        self.label_62 = QtGui.QLabel(self.tab_5)
        self.label_62.setGeometry(QtCore.QRect(420, 180, 148, 31))
        self.label_62.setAlignment(QtCore.Qt.AlignCenter)
        self.label_62.setObjectName(_fromUtf8("label_62"))
        self.textC1G = QtGui.QTextEdit(self.tab_5)
        self.textC1G.setGeometry(QtCore.QRect(100, 280, 100, 31))
        self.textC1G.setObjectName(_fromUtf8("textC1G"))
        self.label_63 = QtGui.QLabel(self.tab_5)
        self.label_63.setGeometry(QtCore.QRect(-20, 280, 148, 31))
        self.label_63.setAlignment(QtCore.Qt.AlignCenter)
        self.label_63.setObjectName(_fromUtf8("label_63"))
        self.tabWidget_2.addTab(self.tab_5, _fromUtf8(""))
        OpenHand.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(OpenHand)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 745, 20))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        OpenHand.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(OpenHand)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        OpenHand.setStatusBar(self.statusbar)

        self.retranslateUi(OpenHand)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(OpenHand)

    def retranslateUi(self, OpenHand):
        OpenHand.setWindowTitle(QtGui.QApplication.translate("OpenHand", "OpenHand", None, QtGui.QApplication.UnicodeUTF8))
        self.pbStartOpenRAVE.setText(QtGui.QApplication.translate("OpenHand", "start OpenRAVE", None, QtGui.QApplication.UnicodeUTF8))
        self.pbRLoadHand.setText(QtGui.QApplication.translate("OpenHand", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("OpenHand", "Select Hand", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("OpenHand", "Experiment", None, QtGui.QApplication.UnicodeUTF8))
        self.pbRLoadExp.setText(QtGui.QApplication.translate("OpenHand", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("OpenHand", "Object", None, QtGui.QApplication.UnicodeUTF8))
        self.pbRLoadObject.setText(QtGui.QApplication.translate("OpenHand", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.pbRGrasp.setText(QtGui.QApplication.translate("OpenHand", "View Grasp", None, QtGui.QApplication.UnicodeUTF8))
        self.pbRInitialPosture.setText(QtGui.QApplication.translate("OpenHand", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.label_46.setText(QtGui.QApplication.translate("OpenHand", "Initial Posture", None, QtGui.QApplication.UnicodeUTF8))
        self.label_55.setText(QtGui.QApplication.translate("OpenHand", "QB3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_57.setText(QtGui.QApplication.translate("OpenHand", "QB2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_58.setText(QtGui.QApplication.translate("OpenHand", "QA1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_60.setText(QtGui.QApplication.translate("OpenHand", "QB1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_61.setText(QtGui.QApplication.translate("OpenHand", "QC2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_64.setText(QtGui.QApplication.translate("OpenHand", "QD1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_65.setText(QtGui.QApplication.translate("OpenHand", "QD2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_71.setText(QtGui.QApplication.translate("OpenHand", "Quality Results", None, QtGui.QApplication.UnicodeUTF8))
        self.label_59.setText(QtGui.QApplication.translate("OpenHand", "QA2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_62.setText(QtGui.QApplication.translate("OpenHand", "QA2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_63.setText(QtGui.QApplication.translate("OpenHand", "QC1", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), QtGui.QApplication.translate("OpenHand", "Visualize Grasps", None, QtGui.QApplication.UnicodeUTF8))

